<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="gfsm" nsURI="http://diverse.inria.fr/gfsm" nsPrefix="gfsm">
  <eClassifiers xsi:type="ecore:EClass" name="GTransition" eSuperTypes="../../fr.inria.diverse.fsm.model/model/fsm.ecore#//Transition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="guard" lowerBound="1" eType="ecore:EClass ../../fr.inria.diverse.expression.model/model/expression.ecore#//BooleanExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GState" eSuperTypes="../../fr.inria.diverse.fsm.model/model/fsm.ecore#//State">
    <eStructuralFeatures xsi:type="ecore:EReference" name="inExpression" lowerBound="1"
        eType="ecore:EClass ../../fr.inria.diverse.expression.model/model/expression.ecore#//IntOperation"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outExpression" lowerBound="1"
        eType="ecore:EClass ../../fr.inria.diverse.expression.model/model/expression.ecore#//IntOperation"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GFinalState" eSuperTypes="#//GState ../../fr.inria.diverse.fsm.model/model/fsm.ecore#//FinalState"/>
  <eClassifiers xsi:type="ecore:EClass" name="GInitialState" eSuperTypes="#//GState ../../fr.inria.diverse.fsm.model/model/fsm.ecore#//InitialState"/>
  <eClassifiers xsi:type="ecore:EClass" name="GFSM" eSuperTypes="../../fr.inria.diverse.fsm.model/model/fsm.ecore#//FSM"/>
</ecore:EPackage>
