<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="abstractcompare" nsURI="http://diverse.inria.fr/abstractcompare"
    nsPrefix="abstractcompare">
  <eClassifiers xsi:type="ecore:EClass" name="Equal">
    <eTypeParameters name="E"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" lowerBound="1" containment="true">
      <eGenericType eTypeParameter="#//Equal/E"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" lowerBound="1" containment="true">
      <eGenericType eTypeParameter="#//Equal/E"/>
    </eStructuralFeatures>
    <eGenericSuperTypes eClassifier="#//AbstractCompare">
      <eTypeArguments eTypeParameter="#//Equal/E"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractCompare" abstract="true">
    <eTypeParameters name="E"/>
  </eClassifiers>
</ecore:EPackage>
